FROM amazonlinux:latest

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum -y update && yum -y install tar gzip gcc-c++ make nodejs && npm install -g n && rm /bin/node && ln -s /usr/local/bin/node /bin/node && n 12

RUN node --version
